
# This workflow will build a Java project with Gradle. This provides a first line of defence against bad commits. For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Build
on: [ pull_request, push ]
jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
        # run on both Linux and Windows
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2.1.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Capture build artifacts
      if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from latest java on one OS
      uses: actions/upload-artifact@v3.0.0
      with:
        name: DashLoader
        path: build/libs
